carrotFacts = function(){

return ["The Wild Carrot is called Queen Anne's Lace.",	
"The World Longest Carrot recorded in 2007 was 5.839 metres (19 feet 1 7/8 inches)",	
"The World  Heaviest Carrot recorded in 1998 was 18.985 lb (8.61kg) (single root mass)",	
"There is a carrot pie flavour jelly bean!",	
"Both of the words in 'Daucus Carota' mean orange.",	
"Carrots were first grown as a medicine not a food.",	
"The average person will consume 10,866 carrots in a lifetime",	
"The Ancient Greeks called carrots 'Karoto'",	
"Carrots, like other food, are travelling nearly 60 per cent further on the UK roads than in the 1970s - read more",	
"Carrots flowers are also called Birds nest, Bees nest and the Devils Plague",	
"Carrots produce more distilled spirit than potatoes. (read more in this history page - 1788)",	
 "Le Roi Carotte is an 1872 operetta by Offenbach",	
"The crisp texture of carrots is the result of the cell walls being stiffened with the indigestible food fibres cellulose, hemicellulose, and lignin.",	
"Tobacconists in France used to put a carrot in their bins to keep their tobacco from drying out.",	
"Jeff Chiplis, from Cleveland has a collection of over 10,000 carrot items.  See his own page",	
"The Japanese word for carrot is 'ninjin'!",	
"In early Celtic literature, the carrot is referred to as the 'Honey Underground'!",	
"Yes there is a carrot beetle!",	
"The classic Bugs Bunny carrot is the 'Danvers' type.",	
"It's a myth that Mel Blanc, the voice of Bugs Bunny, was allergic to carrots - he simply did not like them.",	
"Carrots are not always orange and can also be found in purple, white, red or yellow.",	
"Carrots were the first vegetable to be canned commercially.",	
"Carrots might unlock the secrets of the universe.",
"The carrot belongs to the family Umbelliferae.",
"If you dug a hole to the Earth's center and dropped a Baby Carrot in it, it'd take 42 minutes to get to the bottom.",
"Carrots have one of  the highest content of beta carotene (vitamin A) of all vegetables.",
"The cultivated variety is classified as Daucus carota, variety sativa.",
"You get between 175,000 and 450,000 seeds in a pound - a teaspoon can hold approximately 2000!",
"The Americans know the wild carrot as Queen Anne's Lace, wild carrot, rattlesnake weed & American carrot.",
"The carrot is a member of the parsley family including species such as celery, parsnip, fennel, dill and coriander.",
"If your first name is Carrot it has made you happiest when you are expressing in some creative, artistic way, and not conforming to strict routine.",
"Holtville, California dubs itself 'The Carrot Capital of the World.' with an Annual Festival, now in its 60th year.",	
"The Anglo-Saxons included carrots as an ingredient in a medicinal drink against the devil and insanity.",	
"The Greek foot soldiers who hid in the Trojan Horse were said to have consumed ample quantities of raw carrots to inactivate their bowels.",	
"The above is unlikely to be true. The Trojan Horse is a mythological tale and carrots are GOOD for constipation, so would have the opposite effect, or did they eat lot of carrots before the fight to clear their intestines and avoid any problems during the important moment??",	
"The Ancient Greeks called the plant Philtron or Bird's Nest.",	
"There is a real Carrot Tree, native to Madeira",	
"Gentlemen in Teheran in the 1870's took carrots stewed in sugar as an aphrodisiac to increase the quality and quantity of sperm!",	
"Believe it or not School in the Uk were given official instructions on how to eat carrots!",	
"In Suffolk, Carrots were formerly given as a specific for preserving and restoring the wind of horses.",	
"In August 2005 Ozlem Aydin wrote a thesis on the mathematical analysis of peeling of carrots, to the graduate school of natural and applied sciences of middle east technical university as part of the requirement for a Masters Degree in Food Engineering.",	
"Fuel for Cars? Scientists now believe that bio fuels will be the answer to our energy needs when the oil runs out. One such fuel, perhaps within 10 years, will be carrots - it would take approximately 6000 carrots to drive one mile.",	
"A strong decoction of carrot and root make a very good insecticide.",	
"You get 10 mg of Vitamin A from 20 average carrots. If you dream of carrots - it portends prosperity and health; for a young woman to eat them denotes she will contract an early marriage and be the mother of several hardy children!!",	
"The Victorians had a recipe to destroy crickets – a paste of flour, powdered arsenic, and scraped carrots, placed near their habitations. This was developed because it was discivered that crickets were very fond of carrots."]
}